import type { Lang } from '../i18n';

export const ui = {
  fr: {
    boot: 'Démarrage de imrane-os…',
    menu: { file: 'Fichier', edit: 'Édition', view: 'Présentation', go: 'Aller', help: 'Aide' },
    brandMenu: ['À propos de ce développeur', 'Télécharger le CV', 'Me contacter', 'Code source du site'],
    apps: {
      about: 'À propos',
      finder: 'Projets',
      terminal: 'Terminal',
      notes: 'Parcours',
      skills: 'Compétences',
      mail: 'Contact',
      readme: 'README.md',
    },
    about: {
      role: 'Ingénieur logiciel junior',
      version: 'Version 2026 · Diplômé EMSI',
      specs: [
        ['Processeur', 'Full-stack · React & Node.js'],
        ['Cloud', 'Google Cloud · Azure · Docker'],
        ['IA', 'Gemini · Vertex AI'],
        ['Mémoire', '4 expériences · 1 100+ contributions/an'],
        ['Localisation', 'Casablanca, Maroc'],
        ['Statut', 'Disponible à temps plein'],
      ],
      more: 'Voir les projets',
      contact: 'Me contacter',
    },
    finder: { sidebar: 'Favoris', all: 'Tous les projets', live: 'Ouvrir le site', code: 'Voir le code', back: 'Retour', items: 'éléments', private: 'Code privé', company: "Code de l'entreprise" },
    mail: { to: 'À', subject: 'Objet', subjectValue: 'Opportunité — Ingénieur full-stack', body: "Bonjour Imrane,\n\nJ'ai découvert votre portfolio et j'aimerais échanger avec vous au sujet de…", send: 'Envoyer', copy: "Copier l'e-mail", copied: 'E-mail copié' },
    terminal: {
      welcome: 'Bienvenue sur imrane-os. Tapez « help » pour voir les commandes.',
      help: [
        ['help', 'liste des commandes'],
        ['whoami', 'qui suis-je'],
        ['about', 'ma présentation'],
        ['projects', 'mes projets'],
        ['open <projet>', 'ouvrir un projet (ex. open tunneleads)'],
        ['experience', 'mon parcours'],
        ['skills', 'ma stack'],
        ['contact', 'me joindre'],
        ['theme', 'basculer clair / sombre'],
        ['wallpaper <nom>', 'silk, lake, glass ou dunes'],
        ['lang', 'switch to English'],
        ['clear', 'effacer le terminal'],
      ],
      notFound: 'commande introuvable : ',
      hint: 'Essayez « help ».',
      hire: "Permission accordée. Ouverture de la messagerie… 📬",
      opening: 'Ouverture de ',
      unknownProject: 'Projet inconnu. Projets disponibles : ',
    },
    dockTip: 'Double-cliquez sur une icône ou utilisez le Dock',
    mobileHint: 'Touchez une application',
    noscript: "Imrane Adli — ingénieur logiciel full-stack à Casablanca. React, Node.js, Google Cloud et IA appliquée. Contact : imrane.adli.pro@gmail.com",
  },
  en: {
    boot: 'Starting imrane-os…',
    menu: { file: 'File', edit: 'Edit', view: 'View', go: 'Go', help: 'Help' },
    brandMenu: ['About this developer', 'Download résumé', 'Get in touch', 'Site source code'],
    apps: {
      about: 'About',
      finder: 'Projects',
      terminal: 'Terminal',
      notes: 'Experience',
      skills: 'Skills',
      mail: 'Contact',
      readme: 'README.md',
    },
    about: {
      role: 'Junior Software Engineer',
      version: 'Version 2026 · EMSI graduate',
      specs: [
        ['Processor', 'Full-stack · React & Node.js'],
        ['Cloud', 'Google Cloud · Azure · Docker'],
        ['AI', 'Gemini · Vertex AI'],
        ['Memory', '4 experiences · 1,100+ contributions/yr'],
        ['Location', 'Casablanca, Morocco'],
        ['Status', 'Open to full-time roles'],
      ],
      more: 'See projects',
      contact: 'Get in touch',
    },
    finder: { sidebar: 'Favorites', all: 'All projects', live: 'Open site', code: 'View code', back: 'Back', items: 'items', private: 'Private code', company: 'Company-owned code' },
    mail: { to: 'To', subject: 'Subject', subjectValue: 'Opportunity — Full-stack engineer', body: "Hi Imrane,\n\nI came across your portfolio and would love to talk about…", send: 'Send', copy: 'Copy email', copied: 'Email copied' },
    terminal: {
      welcome: 'Welcome to imrane-os. Type "help" to see available commands.',
      help: [
        ['help', 'list commands'],
        ['whoami', 'who am I'],
        ['about', 'short intro'],
        ['projects', 'my projects'],
        ['open <project>', 'open a project (e.g. open tunneleads)'],
        ['experience', 'my journey'],
        ['skills', 'my stack'],
        ['contact', 'reach me'],
        ['theme', 'toggle light / dark'],
        ['wallpaper <name>', 'silk, lake, glass or dunes'],
        ['lang', 'passer en français'],
        ['clear', 'clear the terminal'],
      ],
      notFound: 'command not found: ',
      hint: 'Try "help".',
      hire: 'Permission granted. Opening mail… 📬',
      opening: 'Opening ',
      unknownProject: 'Unknown project. Available: ',
    },
    dockTip: 'Double-click an icon or use the Dock',
    mobileHint: 'Tap an app',
    noscript: 'Imrane Adli — full-stack software engineer in Casablanca. React, Node.js, Google Cloud and applied AI. Contact: imrane.adli.pro@gmail.com',
  },
} satisfies Record<Lang, unknown>;
